[ENGNP-442] Migrate from Travis to Github Actions
adgear/consent-string pull request #11
Opened 2023-06-12 20:30 UTC by ChristianSassine

Adds Github Actions workflow to replace travis' CI.

Refs : [ENGNP-442]

2023-06-13 18:24 UTC, ChristianSassine commented on .github/workflows/ci.yml
> +        run: make elvis
Seperated `make test` into individual `make` steps to have an easier way to identify which step failed if a failure occurs
<img width="1064" alt="image" src="https://github.com/adgear/consent-string/assets/71024958/c8304660-082f-49b1-918d-ddbeb626f1e9">

2023-06-15 14:30 UTC, berbiche requested changes
Nice work!
Thanks for updating the test setup 😄

2023-06-15 14:30 UTC, berbiche commented on .github/workflows/ci.yml
> +        erlang: ['21.1', '20.3']
Could you update the test Matrix to 
```suggestion
        erlang: ['24', '25', '26']
```

The lowest version we use in our other projects is OTP 24 and will eventually upgrade to 25 or 26.

2023-06-15 19:47 UTC, ChristianSassine commented on .github/workflows/ci.yml
> +        erlang: ['21.1', '20.3']
Yup. I'm trying to use the newest versions locally but it seems to be only working for OTP 24. OTP 25 and OTP 26 give me the same error as in the [GHA](https://github.com/adgear/consent-string/actions/runs/5282129386/jobs/9556648670) : 
<img width="483" alt="image" src="https://github.com/adgear/consent-string/assets/71024958/c9e44f13-566c-4c92-9a83-740c943e2f49">

2023-06-15 20:03 UTC, pdeschen commented on .github/workflows/ci.yml
> +        erlang: ['21.1', '20.3']
Focus. Ditch OTP 26 out if it's not working as-is right now. Let the team do the eventual OTP 26 migration. Here, this is about travis migration.

2023-06-15 20:14 UTC, ChristianSassine commented on .github/workflows/ci.yml
> +        erlang: ['21.1', '20.3']
Alright, I'll keep it at OTP 24 since it's the lowest version that works and that we use.

2023-06-16 15:24 UTC, berbiche approved these changes
LGTM!
Thanks

2023-06-16 15:28 UTC, merged